// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `weixin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.weixin.component;

public final class WeixinServiceHolder extends Ice.ObjectHolderBase<WeixinService>
{
    public
    WeixinServiceHolder()
    {
    }

    public
    WeixinServiceHolder(WeixinService value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof WeixinService)
        {
            value = (WeixinService)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _WeixinServiceDisp.ice_staticId();
    }
}
