// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `weixin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.weixin.component;

public interface WeixinService extends Ice.Object,
                                       _WeixinServiceOperations, _WeixinServiceOperationsNC
{
    public static final String ice_staticId = "::com::lpmas::weixin::component::WeixinService";

    public static final long serialVersionUID = -748104499L;
}
